# data source
ticker: ^GSPC
start: "1930-01-01"  # yfinance supports S&P 500 data back to 1927

# dataset generation
n_samples: 100     # total number of samples to generate

# train / test split
train_ratio: 0.80

# windowing
lookback: 200          # past OHLCV bars
forward: 200           # bars used for reward look-ahead

# reward engine
reward_key: "car"      # car | sharpe | sortino | calmar
fee_bps: 0.2           # 0.2 = 0.02 %
slippage_bps: 0.1
spread_bps: 0.05
overnight_bp: 2.0      # 2 bp per night

# curriculum
curriculum_phases: 3   # 0,1,2
phase0_vol_pct: 40     # % of data closest to median volatility
phase0_skew_max: 0.5

# scaling
scale_meta: "minmax"   # minmax | std
scale_y: False         # keep raw currency units

# disk
parquet_compression: "snappy"  # snappy (fastest, good compression) | zstd (slower, better compression) | gzip (slowest, best compression)
compression_level: null        # compression level (null=default, zstd: 1-22, gzip: 1-9). Lower=faster
chunk_rows: 5_000_000          # rows per chunk for saving/loading large datasets (prevents OOM)
use_fp16: true                 # use float16 for scaled arrays (50% size reduction, sufficient precision)

# data paths
data_dir: "data"                              # base directory for all data files
raw_data_filename: "raw_{ticker}.parquet"     # raw OHLCV data file (ticker will be substituted)
scaler_filename: "meta_scaler.json"           # fitted scaler parameters
samples_filename: "samples_{n}M.parquet"      # generated samples (n in millions)
forward_windows_filename: "forward_windows.parquet"  # pre-computed forward windows (unique idx)

# performance
n_jobs: -1                                    # parallel workers for large datasets (-1=all cores, -2=all but one, 1=no parallelization)

# modelling
# Available model types: transformer | lightgbm | informer | fedformer | patchtst | itransformer | nbeats | nhits
model_type: "transformer"
batch_size: 1024
epochs: 2                    # will usually early-stop earlier
lr: 1e-3

# Common neural network hyperparameters (used by most models)
d_model: 128
nhead: 4
tx_blocks: 4                 # number of transformer blocks (used by transformer-based models)
mlp_ratio: 4
dropout: 0.1

# PatchTST specific parameters
patch_len: 16                # length of each patch
patch_stride: 8              # stride between patches

# N-BEATS specific parameters
nbeats_stack_types: ["trend", "seasonality", "generic"]  # stack types
nbeats_n_blocks: [1, 1, 1]   # number of blocks per stack
nbeats_mlp_units: 512        # MLP units per block
nbeats_shares_weights: false

# NHITS specific parameters
nhits_pools: [1, 2, 4]       # multi-rate pooling sizes
nhits_mlp_units: 512

# LightGBM specific parameters
lgb_linear_tree: true        # use linear tree (hybrid model)
lgb_max_depth: 8
lgb_num_leaves: 256
lgb_subsample: 0.8
lgb_linear_lambda: 0.01

# Position structure and constraints
max_leverage: 5.0            # maximum leverage allowed (gross_exposure / equity)
min_equity: 1000             # minimum account equity

# SL/TP constraints (using multiplier notation)
# Long: sl < 1.0 (e.g., 0.95 = 5% stop), tp > 1.0 (e.g., 1.10 = 10% profit)
# Short: sl > 1.0 (e.g., 1.05 = 5% stop), tp < 1.0 (e.g., 0.90 = 10% profit)
sl_min: 0.50                 # minimum SL multiplier (max 50% loss)
sl_max: 1.50                 # maximum SL multiplier
tp_min: 1.001                # minimum TP multiplier (must exceed costs, adjusted in code)
tp_max: 21.0                 # maximum TP multiplier (20x = 2000% gain)

# Synthetic data generation - NEW STRUCTURE
# Position state (current holdings)
synth_equity_min: 10000              # minimum equity
synth_equity_max: 100000             # maximum equity
synth_long_value_min: 0              # minimum long position value
synth_long_value_max: 50000          # maximum long position value
synth_short_value_min: 0             # minimum short position value  
synth_short_value_max: 50000         # maximum short position value

# Position SL/TP ranges (using multiplier notation)
synth_long_sl_min: 0.50              # long stop loss range
synth_long_sl_max: 0.99              # (e.g., 0.95 = 5% stop)
synth_long_tp_min: 1.01              # long take profit range
synth_long_tp_max: 21.0              # (e.g., 1.10 = 10% profit)
synth_short_sl_min: 1.01             # short stop loss range
synth_short_sl_max: 1.50             # (e.g., 1.05 = 5% stop)
synth_short_tp_min: 0.50             # short take profit range
synth_short_tp_max: 0.99             # (e.g., 0.90 = 10% profit)

# Distribution parameters for sampling
position_value_mean: 10000           # mean for log-normal distribution
position_value_sigma: 1.0            # sigma for log-normal distribution
tp_sl_mean: 0.05                     # mean for truncated normal (after converting to fraction)
tp_sl_sigma: 0.03                    # sigma for truncated normal

# Hold sample generation
hold_state_pct: 0.10                 # percentage of samples with no positions (flat)
hold_action_pct: 0.20                # percentage of samples with no action (keep positions)

# Action search ranges (for predictor optimization, not synth generation)
action_search_samples: 1000  # number of samples for action search

# numerical stability
epsilon: 1.0e-8              # small value to prevent division by zero

# trading calendar
trading_days_per_year: 252   # number of trading days per year for annualization

# curriculum learning
curriculum_vol_window: 20    # window size for volatility calculation in curriculum